### PR TITLE
Allow infinity point for accumulator values

### PR DESCRIPTION
**Pull request by andrewwhitehead**

### CODE REVIEW

**Comment by andrewwhitehead** [comment]
The default accumulator when no entries have been added is infinity, so it needs to be able to deserialize that.

**Comment by swcurran** [comment]
The default accumulator (created immediately after the RevRegDef) has all proofs valid — none of the credentials have been revoked, meaning all are valid.

As such, this is correct behaviour, right?

**Comment by andrewwhitehead** [comment]
To clarify, infinity is the value of the accumulator when no credentials are issued or they have all been revoked. So that means it is the default accumulator when issuance-by-default is not used. Then, every entry that is issued adds one of the tails entries to that value, and every value that is revoked subtracts one. Because the issuer needs to save this state and return to it, we either need to store the infinity point or use a placeholder value. I will have to verify that the proof is not working when the accumulator is infinity, but there are almost certainly published registries with that value.

**Comment by andrewwhitehead** [comment]
It looks like the Witness value can also be infinity, specifically the witness for the only credential in a registry. I think I'm going to have to add newtype wrappers around Accumulator and Witness to allow for infinity values.

In my testing I'm not seeing any issues with infinity as an accumulator. On the verifier side, it computes `t4` in `create_tau_list_values` and `create_tau_list_expected_values` using the accumulator value, for example:

```
    let t4 = Pair::pair2(
        &r_pub_key.htilde.mul(&params.r)?,
        &rev_reg.accum,
        &r_pub_key.g.mul(&params.r_prime)?.neg()?,
        &r_pub_key.h_cap,
    )?;
```

But this essentially results in `Pair::pair(&r_pub_key.g.mul(&params.r_prime)?.neg()?, &r_pub_key.h_cap)` and doesn't create any issues.

**Comment by swcurran** [comment]
@andrewwhitehead  can you make the AnonCreds meeting on Monday at 7am pacific to discuss? We’ll include this  on the agenda.

**Comment by andrewwhitehead** [comment]
Reference from the CKS 2008 paper:

Screenshot 2023-08-02 at 11 55 47

**Comment by swcurran** [comment]
@mikelodder7 — can you take a look again.  Approved?  

@andrewwhitehead — I noticed you added a few more commits. Is this ready for merging or are you still working on it?

**Comment by andrewwhitehead** [comment]
I'm finished with the changes

**Review by berendsliedrecht — APPROVED** [review]
Approved for @mikelodder7

**Pull request merged**
